name: iOS

on:

  push:

  pull_request:

jobs:

  build:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build

        run: |

          xcodebuild \
          -scheme CryptoPulse \
          -destination 'platform=iOS Simulator,name=iPhone 16'
